### ISSUE TITLE
幻觉问题

### ISSUE THREAD

**Issue by linghengzhu** [RUCKBReasoning/text2sql-demo#2]
hi，请问一下有没有办法解决如下的查询幻觉问题
![image](https://github.com/RUCKBReasoning/text2sql-demo/assets/25080478/5922a7dd-c96c-427d-878c-21f81bbe9baf)
对于无法完成的查询，依然会返回一个错误的sql语句，有没有办法识别出这类查询

**Comment by lihaoyang-ruc** [comment]
这个问题很有意思。

我们的模型在训练阶段使用的数据只有成对的“自然语言问题->SQL查询”。因此，在推理的时候，每次拿到一个新问题，模型都会“尽力”地输出一个SQL查询，尽管这个问题可能根本无法完成，但模型并不知道如何“拒绝回答”它。

想从模型层面解决这个问题，其实也很简单，那就是继续往训练数据中添加一些不能回答的样本，也就是“自然语言问题->拒绝回答的理由”。这样就可以让模型学到哪些问题可以回答，哪些不能回答，并给出合理的理由。

**Comment by lihaoyang-ruc** [comment]
如有任何新的疑问，欢迎重新打开这个issue或提出新的issue ;)
