### ISSUE TITLE
中文训练集

### ISSUE THREAD

**Issue by Aroseisarosier** [RUCKBReasoning/text2sql-demo#3]
如果用中文训练集训练，需要做哪些改变呢？我尝试给您发送邮件，可是没有收到回复，可能是被分到垃圾邮箱里了

**Comment by lihaoyang-ruc** [comment]
由于论文目前还处于审稿状态，我们目前还没有开源出用于训练的代码。

除此之外，CodeS目前并不支持中文，它完全在英文语料上进行训练。Demo支持中文是因为我们在后端接了一个翻译API，详情请看我们的README。

如果你想训练一个中文text2sql模型，我建议您准备好成对的训练数据，然后使用中文预训练语言模型来进行微调，比如[baichuan](https://github.com/baichuan-inc/Baichuan2)或者[chatglm](https://github.com/THUDM/ChatGLM3)，他们都提供了方便的微调代码。

**Comment by Aroseisarosier** [comment]
收到，谢谢！




angel_0528
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RUCKBReasoning/text2sql-demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月24日(星期五) 下午4:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RUCKBReasoning/text2sql-demo] 中文训练集 (Issue #3)





 
Closed #3 as completed.
