### ISSUE TITLE
关于BIRD榜分数复现的疑问

### ISSUE THREAD

**Issue by BugMaker-Boyan** [RUCKBReasoning/text2sql-demo#5]
您好，非常感谢您的工作和贡献。

目前我正在复现该工作在BIRD上的结果，存在以下疑问，不知您是否可以解答：
1.  榜上是使用的哪一个model，是否可以提供hf的link？
2.  该model的input prompt和您在这个repo的代码中是一致的吗？在这个repo的代码中我似乎没有看到使用BIRD的external knowledge部分。如果不一致，是否可以提供一下在BIRD上的相关代码呢？

**Comment by lihaoyang-ruc** [comment]
感谢您对本工作的关注。

1. 榜单上使用的模型来自[SFT CodeS-7b](https://huggingface.co/seeklhy/codes-7b-bird-with-evidence)以及 [SFT CodeS-15B](https://huggingface.co/seeklhy/codes-15b-bird-with-evidence)。
2. 这些model的input prompt和现在repo里是一致的，external knowledge直接拼接在question之前，作为question的一部分，它们以分隔符";"隔开：\<external knowledge\> ; \<question\>。

**Comment by vasede** [comment]
您好，请问text2sql-demo里使用的NL2SQL的模型是哪个

**Comment by lihaoyang-ruc** [comment]
我们已经在https://github.com/RUCKBReasoning/codes 公开了推理代码，可以方便地复现BIRD排行榜上的分数。
