### ISSUE TITLE
关于项目使用的是哪个NL2SQL模型的疑问

### ISSUE THREAD

**Issue by vasede** [RUCKBReasoning/text2sql-demo#6]
您好，感谢您百忙之中来回复我的问题！
请问在这个demo中使用的是哪个text-to-sql的模型？能提供论文的名称吗？感谢！

**Comment by lihaoyang-ruc** [comment]
demo中使用的是CodeS，论文正在经历双盲审稿阶段，暂时还不能公开，谢谢理解。
